/* tslint:disable */
/* eslint-disable */
/**
 * Financial Reports API
 * API for accessing company filings, financial data, industry classifications, and related information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@financialreports.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

